# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Bump version and submit a new BETA Build to Google Play"
  lane :beta do
    # Bump version code for uploading
    increment_version_code

    # Get all correct icon sizes from source
    android_appicon(
      appicon_image_file: '../art/CalculatorIconMaster.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap'
    )

    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy (directly) the latest version to PROD in the Google Play"
  lane :prod do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Promote the version in BETA to PROD in the Google Play"
  lane :promote do
    upload_to_play_store(track: 'beta',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
