# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  #desc "Submit a new Beta Build to Crashlytics Beta"
  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(task: "clean assembleRelease")
    supply(track: 'beta')
    #crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Bump version code for uploading
    increment_version_code

    # Get all correct icon sizes from source
    #android_appicon(
    #  appicon_image_file: '../art/CalculatorIconMaster.png',
    #  appicon_icon_types: [:launcher],
    #  appicon_path: 'app/src/main/res/mipmap'
    #)

    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
